algoritmo "Exemplo Para 01"
var
indice: inteiro
nome: caracter
inicio
// enquanto indice < 5 faca
//    escreva("Digite o nome: ")
//    leia(nome)
//    indice := indice + 1
// fimenquanto
// para: é percorrer de um determinado indice até outro
// para <nomeVariavel> de <inicio> ate <fim> faca
para indice de 0 ate 4 faca
   escreva("Digite o nome: ")
   leia(nome)
fimpara
fimalgoritmo
