algoritmo "Exemplo Vetor 01"
var
nomes: vetor[0..2] de caracter // Vetor de 3 posições, começando no 0 até a posição 2
inicio
// Vetor conjunto de espaços para armazenar dados
nomes[0] := "Bernardo"
nomes[1] := "Genesis"
nomes[2] := "José"

nomes[0] := "Fernanda"


escreval("Primeiro nome: ", nomes[0])
escreval("Segundo nome: ", nomes[1])
escreval("Terceiro nome: ", nomes[2])

fimalgoritmo
