algoritmo "Exemplo Vetor 02"
var
numeros: vetor[0..4] de inteiro
soma: inteiro
inicio

escreva("Digite o 1º número: ")
leia(numeros[0])
escreva("Digite o 2º número: ")
leia(numeros[1])
escreva("Digite o 3º número: ")
leia(numeros[2])
escreva("Digite o 4º número: ")
leia(numeros[3])
escreva("Digite o 5º número: ")
leia(numeros[4])

soma := numeros[0] + numeros[1] + numeros[2] + numeros[3] + numeros[4]
escreval("Soma: ", soma)

fimalgoritmo
